sudo: false
language: node_js
node_js:  # note: node v12+ doesn't work with gulp 3
  # - "node"
  # - 12
  - 10
  - 8
  - 7
  - 6
  - 0.8
before_script:
  - npm install -g gulp-cli
script: gulp build
