sudo: false
language: node_js
node_js:  # note: node v12+ doesn't work with gulp 3
  # - "node"
  # - 12
  - 10
  - 8
  - 7
  - 6

install:
  - npm install gulp-cli
  - npm install jest-cli

before_script:
  - npm test

script:
  - gulp build
