sudo: false
language: node_js
node_js:  # note: node v12+ doesn't work with gulp 3
  # - "node"
  # - 12
  - 10
  - 8
  - 7
  - 6
install:
  - npm install -g gulp-cli
  - npm install -g jest-cli
before_script:
  — gulp —version
  — jest —version
script:
  - gulp build
